// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahxjjrmasxiyyhyhbmfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeGpqcm1hc3hpeXloeWhibWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0ODQ1OTgsImV4cCI6MjA1MjA2MDU5OH0.l_lJU418IJppJtHEHFuqiL-2iyP_F6VAg8MurGEzLh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);